org.gradle.jvmargs             = -Xmx4G
org.gradle.parallel            = true
org.gradle.configuration-cache = false

# Fabric
minecraft_version              = 26.3
loader_version                 = 0.19.5
loom_version                   = 1.17-SNAPSHOT
fabric_version                 = 0.161.0+26.3

# Mod
mod_id                         = createnuclear
mod_name                       = Create Nuclear
mod_version                    = 1.3.2-beta.3
maven_group                    = net.nuclearteam.createnuclear
archives_base_name             = createnuclear-fabric
